version: "3.1"

services:
    db:
        image: postgres:14.1-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
            POSTGRES_DB: strapi

    adminer:
        image: adminer:4.8.1-standalone
        ports:
            - 8080:8080
